export enum ClientJobsInfoDB {
    jobId = 'JobID',
    successProfileOrJobDescription = 'Success Profile/Job Description',
    jrtDetailId = 'JRTDetailID',
    jobName = 'Job Name',
    description = 'Description',
    jobFamilyId = 'JobFamilyID',
    jobFamilyName = 'JobFamilyName',
    jobSubFamilyId = 'JobSubFamilyID',
    jobSubFamilyName = 'JobSubFamilyName',
    referenceLevel = 'ReferenceLevel',
    levelName = 'Level Name',
    subLevelName = 'Sub Level Name',
    createdOn = 'Created On',
    createdBy = 'Created By',
    modifiedOn = 'Modified On',
    modifiedBy = 'Modified By',
    shortProfile = 'ShortProfile',
    bicProfileName = 'BICProfileName',
}
